//! The CI synthetic golden (D-OR3 CI posture): a **restrike-vs-restrike
//! regression lock**, never a captured oracle trace (D10). It drives the engine
//! sink over a fixed, hand-authored draw sequence, serializes the canonical
//! `.gbxtrace`, and pins its SHA-256 — asserting byte-stability across runs and
//! platforms exactly as `save_roundtrip_tests`'s
//! `golden_hash_of_a_synthetic_rsav_is_stable` does. Every byte is synthetic
//! (a chosen seed + operand list); no game data is involved.
//!
//! Regenerate the pin by **running** this test and copying the printed digest —
//! never by hand-editing the hash. A change here means the canonical encoding
//! or the sink's event shape changed; that is a deliberate format change (bump
//! `gbxtrace` / the minor projection version and regenerate in the same commit,
//! D-OR3(c)), not something to paper over.

use gbx_engine::rng::EngineRng;
use gbx_oracle::{check_chain, compare, Comparison, Profile, Trace, TraceCollector, TraceHeader};
use sha2::{Digest, Sha256};

/// Fixed synthetic parameters — chosen once, never derived from game data. The
/// operand list deliberately includes `0` (the draw-always edge) and `1`
/// (always-zero result) alongside small and large moduli.
const SEED: u32 = 0x0cab_2026;
const OPERANDS: &[u16] = &[6, 100, 0, 1, 20, 8, 255, 3, 2, 1000];
const ENCOUNTER: &str = "synthetic-prng-golden-v1";

fn golden_header() -> TraceHeader {
    TraceHeader {
        gbxtrace: 1,
        profile: Profile::Prng,
        game: "cotab-v1.3".to_string(),
        seed: SEED,
        encounter: ENCOUNTER.to_string(),
        source: "restrike".to_string(),
        notes: None,
    }
}

/// Drives the engine sink over the fixed operand list and stamps the header on.
fn build_via_engine_sink() -> Trace {
    let collector = TraceCollector::new();
    let mut rng = EngineRng::new(SEED);
    rng.attach_sink(collector.sink());
    for &n in OPERANDS {
        rng.random(n);
    }
    collector.into_trace(golden_header())
}

#[test]
fn synthetic_prng_trace_golden_hash_is_stable() {
    let trace = build_via_engine_sink();

    // It is a genuine, self-consistent chain (the sink emitted real draws).
    assert_eq!(
        check_chain(&trace),
        Ok(()),
        "the golden trace must chain-check"
    );

    // Byte-determinism: building it again yields identical canonical bytes.
    let text = trace.to_canonical_string();
    assert_eq!(
        text,
        build_via_engine_sink().to_canonical_string(),
        "canonical serialization must be byte-deterministic across builds"
    );

    // Parsing then re-serializing is a fixed point (writer/reader agree).
    let reparsed = Trace::parse(&text).expect("golden must re-parse");
    assert_eq!(
        reparsed.to_canonical_string(),
        text,
        "canonical form is a fixed point"
    );

    let hash: String = Sha256::digest(text.as_bytes())
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();

    // Generated by running this test and reading the actual digest — not
    // hand-edited. If this legitimately needs to change, that is a format
    // change (D-OR3(c)): bump the version and regenerate in the same commit.
    const GOLDEN: &str = "9c290b412c46d32bf882c6f4050ce5207cdfde1dbdbc6416a31bce91c5b2634f";
    assert_eq!(
        hash, GOLDEN,
        "synthetic .gbxtrace golden hash changed (canonical bytes:\n{text})"
    );
}

/// The engine-sink path and an independent `gbx_prng` replay produce the same
/// trace on the projection — the sink carries the true stream, restrike vs
/// restrike (a second regression lock, independent of the byte hash).
#[test]
fn engine_sink_and_prng_replay_agree() {
    let via_sink = build_via_engine_sink();

    let mut p = gbx_prng::Prng::new(SEED);
    let mut events = Vec::new();
    for &n in OPERANDS {
        let before = p.state();
        let result = p.random(n);
        let after = p.state();
        events.push(gbx_oracle::TraceEvent::Rng(gbx_oracle::RngEvent {
            before,
            after,
            n: Some(n),
            result: Some(result),
            caller: None,
        }));
    }
    let via_replay = Trace::new(golden_header(), events);

    assert_eq!(compare(&via_sink, &via_replay), Ok(Comparison::Equal));
    // And byte-identical canonical forms.
    assert_eq!(
        via_sink.to_canonical_string(),
        via_replay.to_canonical_string()
    );
}
